# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-10-07 13:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useragent',
            name='user',
        ),
        migrations.AddField(
            model_name='useragent',
            name='agent',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=True, to=settings.AUTH_USER_MODEL, to_field='id'),
            preserve_default=False,
        ),
    ]
