# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-10-07 13:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userProfile', '0003_remove_useragent_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='useragent',
            name='agent',
            field=models.ForeignKey(null=True, on_delete='id', to=settings.AUTH_USER_MODEL, to_field=True),
        ),
    ]
