# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-10-07 13:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0005_auto_20181007_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useragent',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
