# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-10-07 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0006_auto_20181007_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useragent',
            name='agent',
        ),
        migrations.DeleteModel(
            name='UserAgent',
        ),
    ]
