# Generated by Django 2.0.9 on 2018-10-07 13:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userProfile', '0007_auto_20181007_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=12)),
                ('role', models.CharField(max_length=12)),
                ('postOffice', models.CharField(max_length=150)),
                ('language', models.CharField(default='fr', max_length=12)),
                ('agent', models.ForeignKey(null=True, on_delete=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
