# Generated by Django 2.1.1 on 2018-08-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nberCni', models.CharField(max_length=9, unique=True)),
                ('nberRecep', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(default='John', max_length=150)),
                ('surname', models.CharField(default='Doe', max_length=150)),
                ('birthdate', models.CharField(max_length=10)),
                ('birthPlace', models.CharField(max_length=1000)),
                ('nationality', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=9)),
                ('address', models.CharField(max_length=150)),
                ('madePlace', models.CharField(help_text='Lieu où la carte a été établie', max_length=150)),
            ],
        ),
    ]
