# Generated by Django 2.1.1 on 2018-08-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0002_peopleentity_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopleentity',
            name='nberCni',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
    ]
